# -*- coding: utf-8 -*-
"""Raag Tester.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMZTuU935C-jxFqeRkGOIph-E7YGhIxG
"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # 0=all, 1=info, 2=warning, 3=error
import tensorflow as tf

import librosa
import numpy as np

def preprocess_audio(file_path, target_sr=16000):
    # Load audio
    waveform, sr = librosa.load(file_path, sr=target_sr, mono=True)
    waveform = waveform.astype(np.float32)
    return waveform

#from google.colab import drive
#drive.mount('/content/drive')

import tensorflow_hub as hub
import numpy as np
import joblib
import json

# Load classifier and label mapping
xgb_model = joblib.load("../raag_model/xgb_raag_model.joblib")
with open("../raag_model/id2label.json", "r") as f:
    id2label = json.load(f)

# Load YAMNet
yamnet_model = hub.load("https://tfhub.dev/google/yamnet/1")

def predict_raag(file_path):
    waveform = preprocess_audio(file_path)
    _, embeddings, _ = yamnet_model(waveform)
    clip_embedding = np.mean(embeddings.numpy(), axis=0)
    pred_id = xgb_model.predict(clip_embedding.reshape(1, -1))[0]
    return id2label[str(pred_id)]

# Example
print(predict_raag("../Sample_data/test_Bhairav1.mp3"))